import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createDemo,today} from '../dist/planner.js';
const html=fs.readFileSync(new URL('../dist/index.html',import.meta.url),'utf8');
const old=createDemo(today());old.mode='personal';old.goal.title='My original personal goal';
const records={'reflect-ai-v1':JSON.stringify(old)};
function setup(account,cloud={state:null,revision:0}){
 const dom=new JSDOM(html,{url:'https://reflect.example/'});const w=dom.window;
 globalThis.window=w;globalThis.document=w.document;globalThis.localStorage=w.localStorage;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};
 globalThis.setInterval=()=>1;
 for(const [key,value]of Object.entries(records))localStorage.setItem(key,value);
 const bootstrap=document.createElement('script');bootstrap.type='application/json';bootstrap.id='reflect-account';bootstrap.textContent=JSON.stringify(account);document.body.append(bootstrap);
 const workspace=document.createElement('script');workspace.type='application/json';workspace.id='reflect-workspace';workspace.textContent=JSON.stringify(cloud);document.body.append(workspace);
 globalThis.fetch=async(url,options)=>Response.json({revision:JSON.parse(options.body).revision+1});
 return dom;
}
setup({id:'owner-subject',email:'owner@gmail.com',name:'Owner',legacyOwner:true});await import('../dist/app.js?account=owner');
assert.match(document.querySelector('.goal-hero h2').textContent,/My original personal goal/);assert.ok(localStorage.getItem('reflect-ai-v1:owner-subject'));assert.ok(localStorage.getItem('reflect-ai-v1'),'Original backup is preserved');
document.querySelector('[data-action="toggle"]').click();assert.equal(JSON.parse(localStorage.getItem('reflect-ai-v1:owner-subject')).tasks[0].done,true);assert.equal(JSON.parse(localStorage.getItem('reflect-ai-v1')).tasks[0].done,false);
document.querySelector('[data-action="settings"]').click();assert.match(document.querySelector('#modal').textContent,/Signed in as owner@gmail.com/);assert.equal(document.querySelector('form[action="/auth/logout"]').method,'post');
await new Promise(resolve=>setImmediate(resolve));
records['reflect-ai-v1:owner-subject']=localStorage.getItem('reflect-ai-v1:owner-subject');
setup({id:'other-subject',email:'other@gmail.com',name:'Other',legacyOwner:false});await import('../dist/app.js?account=other');
assert.doesNotMatch(document.querySelector('.goal-hero h2').textContent,/My original personal goal/);assert.equal(localStorage.getItem('reflect-ai-v1:other-subject'),null);document.querySelector('[data-action="toggle"]').click();assert.equal(JSON.parse(localStorage.getItem('reflect-ai-v1:other-subject')).mode,'demo');assert.equal(JSON.parse(localStorage.getItem('reflect-ai-v1:owner-subject')).goal.title,'My original personal goal');
await new Promise(resolve=>setImmediate(resolve));
const cloudGoal=createDemo(today());cloudGoal.mode='personal';cloudGoal.goal.title='My saved cloud goal';
setup({id:'cloud-user',email:'new@gmail.com'}, {state:cloudGoal,revision:4});await import('../dist/app.js?account=cloud');
assert.match(document.querySelector('.goal-hero h2').textContent,/My saved cloud goal/);
globalThis.fetch=async()=>{throw new Error('offline');};document.querySelector('[data-action="toggle"]').click();await new Promise(resolve=>setImmediate(resolve));
assert.match(document.querySelector('.storage-error').textContent,/Cloud save is unavailable/);
const pending=JSON.parse(localStorage.getItem('reflect-ai-v1:cloud-user:sync'));assert.equal(pending.revision,4);assert.equal(pending.state.tasks[0].done,true);
globalThis.fetch=async()=>Response.json({error:'Conflict'},{status:409});document.querySelector('[data-action="sync-retry"]').click();await new Promise(resolve=>setImmediate(resolve));assert.match(document.querySelector('.storage-error').textContent,/Another device/);
document.querySelector('[data-action="toggle"]').click();assert.match(document.querySelector('.storage-error').textContent,/Another device/);
records['reflect-ai-v1:cloud-user:sync']=localStorage.getItem('reflect-ai-v1:cloud-user:sync');records['reflect-ai-v1:cloud-user']=localStorage.getItem('reflect-ai-v1:cloud-user');
const newer=structuredClone(cloudGoal);newer.goal.title='A change from my other device';
setup({id:'cloud-user',email:'new@gmail.com'}, {state:newer,revision:5});await import('../dist/app.js?account=recovery');
assert.match(document.querySelector('.goal-hero h2').textContent,/A change from my other device/);assert.ok(localStorage.getItem('reflect-ai-v1:cloud-user:recovered'));assert.equal(localStorage.getItem('reflect-ai-v1:cloud-user:sync'),null);
document.querySelector('[data-action="settings"]').click();assert.ok(document.querySelector('[data-action="export-recovery"]'));
console.log('PASS: account isolation, owner backup migration, cloud hydration, offline backup, conflict blocking, recovery after another device changes the workspace, and signed-in identity/sign-out.');
process.exit(0);
