const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const outputDir=path.resolve(process.env.REFLECT_TEST_OUTPUT_DIR||'test-results');
fs.mkdirSync(outputDir,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1120}});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('reflect-ai-v1')));
 await page.goto(process.env.REFLECT_TEST_URL||'http://127.0.0.1:3000');
 await page.getByRole('heading',{name:'Small steps. Real progress.'}).waitFor();
 await page.screenshot({path:path.join(outputDir,'reflect-demo-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Create your goal'}).click();
 await page.locator('#goal-title').fill('Build my customer support automation demo');
 await page.locator('#goal-success').fill('3 users can submit a request and receive a correct response');
 await page.locator('#goal-why').fill('Make a useful sample for my portfolio');
 const dates=await page.evaluate(async()=>{const m=await import('/planner.js');return {start:m.today(),end:m.addDays(m.today(),55)};});
 await page.locator('#goal-endDate').fill(dates.end);
 await page.getByRole('button',{name:'Shape my plan'}).click();
 await page.locator('#cp-actions-0').fill('Define the support request input\nWrite three realistic sample requests\nChoose the smallest response workflow');
 await page.getByRole('button',{name:'Preview schedule'}).click();
 await page.getByText('12 actions across', {exact:false}).waitFor();
 await page.getByRole('button',{name:'Activate my goal'}).click();
 let data=await read();assert.equal(data.mode,'personal');assert.equal(data.tasks.length,12);assert.equal(data.goal.title,'Build my customer support automation demo');
 await page.getByRole('button',{name:'My plan',exact:true}).click();
 const first=data.tasks[0];
 await page.getByRole('button',{name:'Complete action: '+first.title,exact:true}).click();
 data=await read();assert.equal(data.tasks[0].done,true);
 await page.reload();await page.getByRole('button',{name:'My plan',exact:true}).click();
 await page.getByRole('button',{name:'Mark incomplete: '+first.title,exact:true}).waitFor();
 await page.getByRole('button',{name:'Edit action: '+first.title,exact:true}).click();
 await page.locator('#task-title').fill('Define the support request input and acceptance criteria');
 await page.locator('#task-minutes').fill('15');
 await page.getByRole('button',{name:'Save changes'}).click();
 data=await read();assert.equal(data.tasks[0].minutes,15);assert.ok(data.tasks[0].title.includes('acceptance criteria'));
 const second=data.tasks[1];
 await page.getByRole('button',{name:'Reschedule action: '+second.title,exact:true}).click();
 const later=await page.evaluate(async()=>{const m=await import('/planner.js');return m.addDays(m.today(),3);});
 await page.locator('#task-date').fill(later);
 await page.getByRole('button',{name:'Save changes'}).click();
 assert.equal((await read()).tasks[1].date,later);
 await page.getByRole('button',{name:'Add action',exact:true}).click();
 await page.locator('#task-title').fill('Ask one tester to try the support flow');
 await page.locator('#task-minutes').fill('10');
 await page.getByRole('button',{name:'Add action',exact:true}).last().click();
 assert.equal((await read()).tasks.length,13);
 await page.getByRole('button',{name:'Reflections',exact:true}).click();
 for(const [type,label] of [['weekly','Weekly'],['monthly','Monthly'],['end','End-of-goal']]){
  await page.locator(`.reflection-type`).filter({has:page.getByRole('heading',{name:`${label} reflection`,exact:true})}).getByRole('button',{name:'Open reflection'}).click();
  await page.locator('#reflection-wins').fill(`${label}: The core support workflow is clear and testable.`);
  await page.locator('#reflection-challenges').fill('I needed smaller actions.');
  await page.locator('#reflection-lesson').fill('Test one request type before expanding.');
  if(type==='weekly'){await page.locator('#reflection-next').fill('Test the support flow with a difficult request');await page.locator('#reflection-minutes').fill('10');}
  await page.getByRole('button',{name:'Save reflection'}).click();
 }
 data=await read();assert.equal(data.reflections.length,3);assert.equal(data.tasks.length,14);assert.ok(data.tasks.some(t=>t.title==='Test the support flow with a difficult request'));
 await page.getByRole('button',{name:'Revisit',exact:true}).last().click();
 await page.locator('#reflection-wins').fill('Weekly: I tested the core support workflow.');
 await page.locator('#reflection-add').check();
 await page.locator('#reflection-next').fill('Test the support flow with two difficult requests');
 await page.getByRole('button',{name:'Save reflection'}).click();
 data=await read();assert.equal(data.reflections.length,3);assert.equal(data.tasks.length,14);assert.ok(data.tasks.some(t=>t.title==='Test the support flow with two difficult requests'));
 await page.reload();await page.getByRole('button',{name:'Reflections',exact:true}).click();
 assert.equal(await page.locator('.history-item').count(),3);
 await page.screenshot({path:path.join(outputDir,'reflect-journal-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Workspace settings and backups'}).click();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();const download=await downloadPromise;const file=await download.path();const backup=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(backup.reflections.length,3);
 await page.getByRole('button',{name:'Import',exact:true}).click();
 await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 await page.getByRole('button',{name:'Restore backup'}).click();assert.equal((await read()).reflections.length,3);
 await page.getByRole('button',{name:'Today',exact:true}).click();
 await page.getByRole('button',{name:'Start focus',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).waitFor();
 await page.getByRole('button',{name:'Pause',exact:true}).click();await page.getByRole('button',{name:'Reset focus timer'}).click();assert.equal(await page.locator('#timer-display').innerText(),'25:00');
 await page.screenshot({path:path.join(outputDir,'reflect-personal-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile must not overflow');
 await page.screenshot({path:path.join(outputDir,'reflect-mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'My plan',exact:true}).click();
 await page.getByRole('button',{name:'Next goal'}).click();
 await page.locator('#goal-title').fill('Finish one focused task');await page.locator('#goal-success').fill('One task finished and reflected on');
 await page.locator('#goal-endDate').fill(dates.start);
 for(const cb of await page.locator('[name="workday"]').all())await cb.check();
 await page.getByRole('button',{name:'Shape my plan'}).click();await page.getByRole('button',{name:'Preview schedule'}).click();
 await page.locator('#form-error').filter({hasText:'can fit 1 action'}).waitFor();
 for(let i=4;i>1;i--)await page.getByRole('button',{name:`Remove checkpoint ${i}`}).click();
 await page.locator('#cp-actions-0').fill('Complete one focused task');await page.getByRole('button',{name:'Preview schedule'}).click();
 await page.getByRole('button',{name:'Activate my goal'}).click();data=await read();assert.equal(data.archives.length,1);assert.equal(data.tasks.length,1);
 await page.getByRole('button',{name:'Workspace settings and backups'}).click();await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Open goal'}).click();data=await read();assert.equal(data.tasks.length,14);assert.equal(data.reflections.length,3);assert.equal(data.archives.length,1);
 await page.setViewportSize({width:320,height:740});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'small mobile must not overflow');
 await page.getByRole('button',{name:'My plan',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile plan must not overflow');
 await page.getByRole('button',{name:'Reflections',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile journal must not overflow');
 assert.deepEqual(errors,[],'No browser JavaScript errors');
 console.log('PASS: goal creation; realistic schedule; completion and reload; action editing; rescheduling; add action; weekly/monthly/end reflections; next-step deduplication; export/import; focus timer; capacity error recovery; goal archiving/restoration; mobile layouts; no JavaScript errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
